stages:
  - verify

before_script:
  - py --version
  - py -m pip install --upgrade pip
  - py -m pip install -r requirements.txt

python_syntax:
  stage: verify
  script:
    - py -m compileall app

black:
  stage: verify
  script:
    - py -m black --check app

ruff:
  stage: verify
  script:
    - py -m ruff check app

isort:
  stage: verify
  script:
    - py -m isort --check-only app

flake8:
  stage: verify
  script:
    - py -m flake8 app

bandit:
  stage: verify
  script:
    - py -m bandit -r app

detect_secrets:
  stage: verify
  script:
    - py -m detect_secrets scan --all-files

pip_audit:
  stage: verify
  script:
    - py -m pip_audit
  allow_failure: true