image: python:3.11

stages:
  - verify

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt

python_syntax:
  stage: verify
  script:
    - python -m compileall app

black:
  stage: verify
  script:
    - black --check app